//2021.3.19 작성
//2주차 수업 예제 코드

using System;

namespace _20210319
{
    class Program
    {
        static void Main(string[] args)
        {
            //코드2-23
            int a = 273;
            int b = 52;
            Console.WriteLine(a + b);
            Console.WriteLine(a - b);
            Console.WriteLine(a * b);
            Console.WriteLine(a / b);
            Console.WriteLine(a % b);
            //코드2-24
            int a1 = 2147483640;
            int b1 = 52273;
            Console.WriteLine(a1+b1);
        }
    }
}
